version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/build:/etc/nginx/build
    networks:
      - app_network

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: win
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    image: be
    container_name: be
    build:
      context: ./travel-agency-backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - nginx
    ports:
      - "3001:3001"
    networks:
      - app_network
    command: npm run start:dev

  # fe:
  #   image: fe
  #   container_name: fe
  #   build:
  #     context: ./travel-agency
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - db
  #     - nginx
  #     - be
  #   environment:
  #     APP_PORT: 3000
  #     APP_DB_TYPE: postgres
  #     APP_DB_HOST: db
  #     APP_DB_PORT: 5432
  #     APP_DB_NAME: quickwage
  #     APP_DB_USERNAME: root
  #     APP_DB_PASSWORD: 12345
  #     APP_DB_MAXCONNECTIONS: 100
  #     APP_MAIL_KEY:
  #     JWT_TOKEN_EXPIRY: "1h"
  #   networks:
  #     - app_network
  #   command: npm run start

volumes:
  pgdata:
networks:
  app_network:
    driver: bridge
